### ISSUE TITLE
stop logging if you turn the Mobile

### ISSUE THREAD

**Issue by Ben17** [tjanson/WifiLocationLogger#11]
if automatic picture turn is on the logging will stop if you turn the mobile if automatic is off the logging will continue.

**Comment by tjanson** [comment]
Can you confirm that this happens with the [latest version](https://github.com/tjanson/WifiLocationLogger/releases/tag/v0.1-alpha.4)? I thought this was fixed (see #6).

**Comment by Ben17** [comment]
it´s fixed in the latest version
