### ISSUE TITLE
Change standart SSID Filter to       .*[Ff]reifunk.*

### ISSUE THREAD

**Issue by Frief84** [tjanson/WifiLocationLogger#15]
Change standart SSID Filter to       .(star)[Ff]reifunk.(star)
to catch all Freifunk-Networks

**Comment by tjanson** [comment]
It’s currently [`(.*)(F|f)reifunk(.*)`](https://github.com/tjanson/WifiLocationLogger/blob/master/app/src/main/res/values/strings.xml#L14), which is equivalent, unless I’m missing something.

**Comment by Frief84** [comment]
Ah ok sorry ... The last SSID Filter apparently seams to remain at update

**Comment by tjanson** [comment]
True. But that’s a feature ;)
