### ISSUE TITLE
Maintenance status & License

### ISSUE THREAD

**Issue by IzzySoft** [tjanson/WifiLocationLogger#22]
Just wondering if this project is still maintained (no commits for almost 4 years). If not, may I suggest to archive it (via its settings here in Github) to make it clear to see?

**Comment by tjanson** [comment]
Well I suppose it is maintained in the sense that I’d merge PRs if there were any. So I’m ambivalent about archiving it.

This project never was anything more than a quick and dirty attempt to log some data for the Freifunk community. Have you tried building it? It might still work. (If it doesn’t, I’ll add a note so others don’t waste 
 their time.)

**Comment by IzzySoft** [comment]
Thanks for your reply! So let's say it's "no longer actively developed"?

Background for my question is [your app is in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.tomjanson.wifilocationlogger), and I just ran my "annual inventory". One step of that was checking with each project that didn't have any commit for more than 2 years :wink:

So is it OK for you if I use above phrase and link to this issue?

**Comment by tjanson** [comment]
Yes, sure, that’s accurate.

**Comment by IzzySoft** [comment]
Done, thanks! (Visible after the next sync, latest tomorrow evening).

**Comment by IzzySoft** [comment]
PS: What license do you use for your app, @tjanson? Couldn't find any mention in readme or source.

**Comment by tjanson** [comment]
I’m not opposed to using a FOSS license or even releasing the code into the public domain, but since I’m strictly speaking not the sole author, I can’t unilaterally do so now.

@MPW1412 Do you agree to release [your contribution](https://github.com/tjanson/WifiLocationLogger/pull/10) into the public domain? (Or MIT / whatever, if you prefer?)

**Comment by MPW1412** [comment]
Sure, do whatever you want with the code. It's just a few lines.

Freifunk Münsterland is developing another App at the moment to display signal strength on a map.

**Comment by tjanson** [comment]
Interesting, can you give me a link @MPW1412 ? And thanks for your permission.

@IzzySoft Consider the code dedicated to the public domain using the [Creative Commons *CC0 1.0* dedication](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by IzzySoft** [comment]
Thanks @tjanson & @MPW1412! Added that to the app's description (should show up with tomorrow's sync).
