### ISSUE TITLE
Master compiliert, aber apk nicht installierbar

### ISSUE THREAD

**Issue by MPW1412** [tjanson/WifiLocationLogger#8]
Hallo,

ich wollte mir gerade Mal das master-Branch, dass ja etwas vor der aktuell publizierten Version liegt, kompilieren und installieren. Kompiliert auch alles ohne Fehlermeldung, aber bei der Installation der Datei app-release-unsigned.apk kam einfach nur der Hinweis, dass die Software nicht installiert wurde.

Auch vorheriges Deinstallieren der älteren Version half nicht.

Hast du eine Idee woran das liegt? Würde gerne lernen es selbst zu kompilieren. Habe folgendes ausgeführt:

`JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64/ ANDROID_HOME=/opt/android-sdk-linux ./gradlew
JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64/ ANDROID_HOME=/opt/android-sdk-linux ./gradlew assemble`

Grüße
MPW

**Comment by tjanson** [comment]
Also ich verwende [Android Studio](https://developer.android.com/tools/studio/index.html) und kenne mich tatsächlich mit dem CLI-Weg, zu kompilieren, überhaupt nicht aus.
Aber ich finde A.S. eh ziemlich sinnvoll (und ich bin im allgemeinen kein Fan von IDEs, das heißt also was). Den Weg würde ich also gehen.

**Comment by MPW1412** [comment]
Danke für den Tipp, hab den Fehler gefunden: Die app-release.apk geht nicht, bisher kompiliert der nur die Debugversion. Vermutlich fehlt da noch was in der Buildchain. Aber ist ja auch alles noch experimentell.

Denn auch Android Studio baut derzeit nur die Debugversion. Die funktioniert jedenfalls, wenn man obigen Befehl nutzt.

**Comment by tjanson** [comment]
Interessant. Meine erste Vermutung ist, dass das Google Location API für die Release-Version einen API-Key haben will oder sowas. Wird sich zeigen.

**Comment by MPW1412** [comment]
Genau, irgendwie sowas. Bin da auch (noch) relativ unerfahren. Die Debug-Version reicht ja erstmal vollkommen.
